server:
  port: 7071
spring:
  redis:
    host: 192.168.0.100
    port: 6379
    password: 123456
  rabbitmq:
    host: 192.168.0.100
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
#这里通过配置文件进行主键自增
