server:
  port: 7069

spring:
  redis:
    host: 192.168.0.100
    port: 6379
    password: 123456
  rabbitmq:
    host: 192.168.0.100
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual